#include <iostream>
#include <iomanip>
#include <map>
#include <fstream>
#include <sstream>
#include <exception>
#include <cctype>
#include <algorithm>
#include <locale>
#include <set>

using std::cout;
using std::endl;
using std::string;
using std::map;
using std::ifstream;
using std::ofstream;
using std::getline;
using std::exception;
using std::runtime_error;
using std::istringstream;
using std::stringstream;
using std::left;
using std::right;
using std::setw;
using std::ispunct;
using std::cin;
using std::find;
using std::transform;
using std::locale;
using std::set;
